from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = Path(__file__).resolve().parent / "outputs"
DEFAULT_DATASET = "SAM3"

SUMMARY_COLUMNS = [
    "tool",
    "dataset",
    "output_dir",
    "markdown_path",
    "html_path",
    "metadata_path",
    "total_characters",
    "markdown_headings",
    "markdown_tables",
    "html_tables",
    "image_references",
    "image_files",
    "figure_caption_count",
    "formula_marker_count",
    "metadata_pages",
    "metadata_chunks",
    "metadata_images",
    "notes",
]

MANUAL_SCORE_COLUMNS = [
    "tool",
    "text_accuracy_1_to_5",
    "reading_order_1_to_5",
    "table_quality_1_to_5",
    "formula_quality_1_to_5",
    "header_footer_handling_1_to_5",
    "tiny_text_quality_1_to_5",
    "multi_column_order_1_to_5",
    "figure_caption_quality_1_to_5",
    "markdown_usability_1_to_5",
    "rag_readiness_1_to_5",
    "notes",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate OCR outputs that were generated by separate OCR repositories."
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help="Root folder containing <tool>/<dataset>/ OCR outputs.",
    )
    parser.add_argument(
        "--dataset",
        default=DEFAULT_DATASET,
        help="Dataset/output folder name under each tool folder. Default: SAM3.",
    )
    parser.add_argument(
        "--tools",
        nargs="*",
        default=None,
        help="Tool names to evaluate. If omitted, all folders under output-root are used.",
    )
    parser.add_argument(
        "--summary-path",
        type=Path,
        default=None,
        help="Optional path for summary CSV. Default: <output-root>/<dataset>_summary.csv",
    )
    parser.add_argument(
        "--manual-score-path",
        type=Path,
        default=None,
        help="Optional path for manual score CSV. Default: <output-root>/<dataset>_manual_score.csv",
    )
    return parser.parse_args()


def resolve_path(path: Path) -> Path:
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def read_text(path: Path | None) -> str:
    if not path or not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def load_json(path: Path | None) -> dict[str, Any]:
    if not path or not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except json.JSONDecodeError:
        return {}


def find_first(path: Path, patterns: list[str]) -> Path | None:
    for pattern in patterns:
        matches = sorted(path.glob(pattern))
        if matches:
            return matches[0]
    return None


def count_markdown_tables(markdown: str) -> int:
    rows = [
        line
        for line in markdown.splitlines()
        if line.strip().startswith("|") and line.strip().endswith("|")
    ]
    return len(rows)


def count_figure_captions(text: str) -> int:
    pattern = re.compile(r"\b(figure|fig\.|caption|image|table|圖|圖片|表格)\b", re.IGNORECASE)
    return len(pattern.findall(text))


def count_formula_markers(text: str) -> int:
    return text.count("$$") + len(re.findall(r"\\\(|\\\[", text)) + text.count("$")


def get_metadata_number(metadata: dict[str, Any], keys: list[str]) -> str:
    for key in keys:
        value = metadata.get(key)
        if value is not None:
            return str(value)
    return ""


def discover_tools(output_root: Path, requested_tools: list[str] | None) -> list[str]:
    if requested_tools:
        return requested_tools
    if not output_root.exists():
        return []
    return sorted(path.name for path in output_root.iterdir() if path.is_dir())


def evaluate_tool(output_root: Path, dataset: str, tool: str) -> dict[str, str | int]:
    output_dir = output_root / tool / dataset
    markdown_path = find_first(output_dir, ["*.md", "**/*.md"])
    html_path = find_first(output_dir, ["*.html", "**/*.html"])
    metadata_path = find_first(output_dir, ["*metadata*.json", "output.json", "**/*metadata*.json", "**/output.json"])

    markdown = read_text(markdown_path)
    html = read_text(html_path)
    metadata = load_json(metadata_path)
    combined_text = "\n".join(part for part in [markdown, html] if part)

    image_files = list(output_dir.glob("*.png"))
    image_files += list(output_dir.glob("*.jpg"))
    image_files += list(output_dir.glob("*.jpeg"))
    image_files += list(output_dir.glob("*.webp"))

    notes = ""
    if not output_dir.exists():
        notes = "output directory not found"
    elif not markdown and not html:
        notes = "no markdown or html output found"

    return {
        "tool": tool,
        "dataset": dataset,
        "output_dir": str(output_dir),
        "markdown_path": str(markdown_path) if markdown_path else "",
        "html_path": str(html_path) if html_path else "",
        "metadata_path": str(metadata_path) if metadata_path else "",
        "total_characters": len(combined_text),
        "markdown_headings": sum(1 for line in markdown.splitlines() if line.startswith("#")),
        "markdown_tables": count_markdown_tables(markdown),
        "html_tables": len(re.findall(r"<table\b", html, flags=re.IGNORECASE)),
        "image_references": len(re.findall(r"!\[[^\]]*\]\([^)]+\)", markdown)),
        "image_files": len(image_files),
        "figure_caption_count": count_figure_captions(combined_text),
        "formula_marker_count": count_formula_markers(combined_text),
        "metadata_pages": get_metadata_number(metadata, ["num_pages", "pages_count", "page_count"]),
        "metadata_chunks": get_metadata_number(metadata, ["total_chunks", "num_chunks", "chunk_count"]),
        "metadata_images": get_metadata_number(metadata, ["total_images", "num_images", "image_count"]),
        "notes": notes,
    }


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def make_manual_score_rows(tools: list[str]) -> list[dict[str, str]]:
    rows = []
    for tool in tools:
        row = {column: "" for column in MANUAL_SCORE_COLUMNS}
        row["tool"] = tool
        rows.append(row)
    return rows


def main() -> int:
    args = parse_args()
    output_root = resolve_path(args.output_root)
    summary_path = resolve_path(args.summary_path) if args.summary_path else output_root / f"{args.dataset}_summary.csv"
    manual_score_path = (
        resolve_path(args.manual_score_path)
        if args.manual_score_path
        else output_root / f"{args.dataset}_manual_score.csv"
    )

    tools = discover_tools(output_root, args.tools)
    if not tools:
        print(f"No OCR output folders found under: {output_root}")
        return 1

    rows = [evaluate_tool(output_root, args.dataset, tool) for tool in tools]
    write_csv(summary_path, SUMMARY_COLUMNS, rows)

    if not manual_score_path.exists():
        write_csv(manual_score_path, MANUAL_SCORE_COLUMNS, make_manual_score_rows(tools))

    print(f"Evaluated tools: {', '.join(tools)}")
    print(f"Summary: {summary_path}")
    print(f"Manual score template: {manual_score_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
